version: '3.1'

services:
  client:
    image: "myapp-web:${WEBTAG}"
    build:
      context: ./client
      dockerfile: client.Dockerfile 
    environment:
      - "REACT_APP_API_URL=http://backend:5000"      
    ports:
      - "3000:3000" 
    networks:
      - webappnetwork

  backend:
    image: "myapp-api:${APITAG}"
    build:
      context: .
      dockerfile: backend.Dockerfile 
    environment:
      - Database=mongodb://mongo:27017/nodetest
    ports:
      - "5000:5000"   
    networks:
      - webappnetwork

  mongo:
    image: mongo
    restart: always    
    ports:
     - 27017:27017
    networks:
      - webappnetwork
 
    
networks:
    webappnetwork:
        driver: bridge
        